package model;
// Generated 4/jun/2014 17:47:26 by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CarService generated by hbm2java
 */
@Entity
@Table(name="car_service"
    ,catalog="Setare"
)
public class CarService  implements java.io.Serializable {


     private Integer id;
     private Subsidiary subsidiaryByDropOffSubsidiaryId;
     private User user;
     private Car car;
     private Subsidiary subsidiaryByPickUpSubsidiaryId;
     private Date serviceBegin;
     private Date serviceEnd;
     private boolean gps;
     private boolean babySeat;
     private boolean insurance;
     private boolean additionalDriver;
     private BigDecimal finalPrice;

    public CarService() {
    }

    public CarService(Subsidiary subsidiaryByDropOffSubsidiaryId, User user, Car car, Subsidiary subsidiaryByPickUpSubsidiaryId, Date serviceBegin, Date serviceEnd, boolean gps, boolean babySeat, boolean insurance, boolean additionalDriver, BigDecimal finalPrice) {
       this.subsidiaryByDropOffSubsidiaryId = subsidiaryByDropOffSubsidiaryId;
       this.user = user;
       this.car = car;
       this.subsidiaryByPickUpSubsidiaryId = subsidiaryByPickUpSubsidiaryId;
       this.serviceBegin = serviceBegin;
       this.serviceEnd = serviceEnd;
       this.gps = gps;
       this.babySeat = babySeat;
       this.insurance = insurance;
       this.additionalDriver = additionalDriver;
       this.finalPrice = finalPrice;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="drop_off_subsidiary_id", nullable=false)
    public Subsidiary getSubsidiaryByDropOffSubsidiaryId() {
        return this.subsidiaryByDropOffSubsidiaryId;
    }
    
    public void setSubsidiaryByDropOffSubsidiaryId(Subsidiary subsidiaryByDropOffSubsidiaryId) {
        this.subsidiaryByDropOffSubsidiaryId = subsidiaryByDropOffSubsidiaryId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="car_id", nullable=false)
    public Car getCar() {
        return this.car;
    }
    
    public void setCar(Car car) {
        this.car = car;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pick_up_subsidiary_id", nullable=false)
    public Subsidiary getSubsidiaryByPickUpSubsidiaryId() {
        return this.subsidiaryByPickUpSubsidiaryId;
    }
    
    public void setSubsidiaryByPickUpSubsidiaryId(Subsidiary subsidiaryByPickUpSubsidiaryId) {
        this.subsidiaryByPickUpSubsidiaryId = subsidiaryByPickUpSubsidiaryId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="service_begin", nullable=false, length=19)
    public Date getServiceBegin() {
        return this.serviceBegin;
    }
    
    public void setServiceBegin(Date serviceBegin) {
        this.serviceBegin = serviceBegin;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="service_end", nullable=false, length=19)
    public Date getServiceEnd() {
        return this.serviceEnd;
    }
    
    public void setServiceEnd(Date serviceEnd) {
        this.serviceEnd = serviceEnd;
    }

    
    @Column(name="gps", nullable=false)
    public boolean isGps() {
        return this.gps;
    }
    
    public void setGps(boolean gps) {
        this.gps = gps;
    }

    
    @Column(name="baby_seat", nullable=false)
    public boolean isBabySeat() {
        return this.babySeat;
    }
    
    public void setBabySeat(boolean babySeat) {
        this.babySeat = babySeat;
    }

    
    @Column(name="insurance", nullable=false)
    public boolean isInsurance() {
        return this.insurance;
    }
    
    public void setInsurance(boolean insurance) {
        this.insurance = insurance;
    }

    
    @Column(name="additional_driver", nullable=false)
    public boolean isAdditionalDriver() {
        return this.additionalDriver;
    }
    
    public void setAdditionalDriver(boolean additionalDriver) {
        this.additionalDriver = additionalDriver;
    }

    
    @Column(name="final_price", nullable=false, precision=10)
    public BigDecimal getFinalPrice() {
        return this.finalPrice;
    }
    
    public void setFinalPrice(BigDecimal finalPrice) {
        this.finalPrice = finalPrice;
    }




}


